# Site settings
name: Muayad R. Qanadilo
email: muayadq@gmail.com
canonical_url: http://hala3ammi.com/
keywords: "Software Engineer, PHP, Java, Javascript, MYSQL, OOP, Design Patterns, Startups, Agile"
skills: "Senior Software Engineer in Amman, Jordan"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/muayadq/
  # - title: medium
  #   url: https://medium.com/@cgroom
  - title: twitter
    url: https://twitter.com/Hala3amme
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
